name: Melhoria
description: Propor uma funcionalidade ou mudanca na interface
labels: ["enhancement"]
body:
  - type: textarea
    id: problema
    attributes:
      label: Qual problema isso resolve
    validations:
      required: true

  - type: textarea
    id: proposta
    attributes:
      label: Proposta
    validations:
      required: true

  - type: textarea
    id: alternativas
    attributes:
      label: Alternativas consideradas
